version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: zephyr-mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-password}'
      MYSQL_DATABASE: zephyr
    expose:
      - 3306
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - '${MYSQL_DIR}/conf/my.cnf:/etc/mysql/my.cnf'
      - '${MYSQL_DIR}/logs:/var/log/mysql'
      - '${MYSQL_DIR}/data:/var/lib/mysql'

  zookeeper: 
    image: zookeeper:3.4.10
    container_name: zephyr-zookeeper
    privileged: true
    expose: 
      - 2181
    ports: 
      - 2181:2181