version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: zephyr-mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASS: password
    expose:
      - 3306
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - ${ZEPHYR_WORKSPACE:-~/.zephyr}/data/mysql:/var/lib/mysql

  zookeeper: 
    image: zookeeper:3.4.10
    container_name: zephyr-zookeeper
    privileged: true
    expose: 
      - 2181
    ports: 
      - 2181:2181
  
  redis:
    image: redis:6.0.5
    expose: 
      - 6379
    ports: 
      - '6380:6379'
    container_name: zephyr-redis  